In [ ]:
import pandas as pd
import re
from datetime import datetime

# Definir o caminho do arquivo CSV numa variável para facilitar a leitura e manutenção do código

CAMINHO = r'C:\\Users\\luiso\\Downloads\\SCTECH\\turma-visualizacao-de-dados\\alunos\\luis_oliveira\\semana_04\\base_rh.csv'

# para ler o arquivo CSV, é necessário especificar o separador, a codificação e o formato decimal   

df = pd.read_csv(CAMINHO, sep=';', encoding='cp1252', decimal=',')

# Confirmar que as importações funcionaram corretamente

print('Dados carregados com sucesso!')
print(f' Total de linhas : {df.shape[0]}')   
print(f' Total de colunas : {df.shape[1]}')

Dados carregados com sucesso!
 Total de linhas : 1000
 Total de colunas : 10

In [10]:
# Exibir as primeiras linhas do DataFrame para verificar se os dados foram carregados corretamente
# Convercionado as 5 primeiras linhas do DataFrame para uma tabela mais legível usando o método head() do pandas

df.head(3)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo

In [11]:
df.tail(3)      # Exibir as últimas linhas do DataFrame para verificar se os dados foram carregados corretamente
                # Se o arquivo tiver 1.000 linhas, o tail deve mostrar os IDs proximos de 1.000, como 998, 999 e 1.000

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [12]:
# df.columns()  # Exibir os nomes das colunas para verificar se foram importados corretamente
# .tolist()     # Converter os nomes das colunas para uma lista para facilitar a manipulação posterior

print('Colunas do dataset: ')
print(df.columns.tolist())

Colunas do dataset:
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [14]:
# Diagnóstico: Tipos e Nulos
# Exibir informações sobre os tipos de dados e a presença de valores nulos em cada coluna usando o método info() do pandas

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

In [ ]:
# Cria uma tabela de True/False indicando a presença de valores nulos em cada célula do DataFrame usando o método isnull() do pandas
# .sum() para obter a soma total de nulos por coluna, ou seja, quantos valores nulos existem em cada coluna do DataFrame

print('Quantidade de valores nulos por coluna:  ')
print(df.isnull().sum())

print()

# Percentual de nulo 
# len(df) para obter o número total de linhas do DataFrame, e calcular o percentual de valores nulos em cada coluna dividindo a quantidade de nulos pela quantidade total de linhas e multiplicando por 100

print('Percentual de valores nulos por coluna:  ')
print((df.isnull().sum() / len(df)) * 100)

SyntaxError: '(' was never closed (465990744.py, line 5)