In [6]:
import pandas as pd
import re
from datetime import datetime

In [9]:
#pd.read_csv() # para ler arquivos .csv
# CAMINHO = onde esta o arquivo. como ele esta na mesma pasta que este notebook.
# basta passar o nome do arquivo, entre aspas, para a função ler o arquivo e criar um DataFrame (tabele) com os dados.

CAMINHO = r"C:\Users\leogo\OneDrive\Documentos\SCTEC\GitHub\turma-visualizacao-de-dados\alunos\Leo_Gobel\Semana_04\base_rh.csv"

df = pd.read_csv(
    CAMINHO,
    sep=';',            # separador de colunas é ';' e não ','
    encoding='cp1252',  # encoding do windowns, para ler acentos
    decimal=','         #virgula é como separador decimal
)   

print('dados carregados com sucesso!')
print(f' Total de Linhas : {df.shape[0]}')
print(f' Total de colunas: {df.shape[1]}')

dados carregados com sucesso!
 Total de Linhas : 1000
 Total de colunas: 10

In [11]:
# df.head 

df.head(5)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [12]:
# df.tail (n) # para ver as ultimas linhas da tabela e confirmar que os dados foram lidos corretamente.
#serve para confirmar que o final tambem foi lido corretamente e para ver se tem alguma informação importante no final da tabela ( ex: rodape, notas)


df.tail(10)

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
990,991,Sr. Vicente Silveira,Produção,Gerente,8026.70,11/07/2021,F,55,Viúvo,Inativo
991,992,Emanuel da Cruz,Logística,Gerente,12572.11,30/01/2024,M,33,Viúvo,Ativo
992,993,Enrico Monteiro,RH,Coordenador,14677.33,26/12/2017,M,52,Divorciado,Inativo
993,994,Ana Lívia Cardoso,RH,Coordenador,14912.48,22/10/2015,M,27,Solteiro,Inativo
994,995,Fernando Monteiro,RH,Assistente,10983.02,09/01/2023,F,42,Viúvo,Ativo
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [13]:
# df.columns # para ver os nomes das colunas e confirmar que foram lidos corretamnte e que estao no formato esperado (sem espaço, sem caracteres estranho)
# .tolist() para transformar o index de colunas em uma lista e facilitar a manipulação dos nomes das colunas (para renomear, para acessar as colunas...)


print('colunas do dataset :')
print(df.columns.tolist())

colunas do dataset :
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

- Diagnosticos: Tipos e Nulos

In [14]:
df.info

<bound method DataFrame.info of      ID_Funcionario                 Nome Departamento        Cargo   Salario  \
0                 1          Julia Nunes    Logística  Coordenador   9088.34
1                 2   Sr. Gustavo Duarte           TI      Gerente   8155.98
2                 3  Srta. Mariana Cunha           RH  Coordenador  14027.93
3                 4   Ana Sophia da Cruz     Produção      Técnico   6647.97
4                 5    Dr. Nicolas Pinto     Produção      Gerente   8730.19
..              ...                  ...          ...          ...       ...
995             996       Matheus Aragão   Financeiro     Analista  11389.03
996             997         Ryan Martins   Financeiro     Analista  14060.42
997             998    Isabelly Ferreira           TI      Gerente   2348.73
998             999        Thales Farias     Produção     Analista   9430.62
999            1000   Sra. Maysa Costela     Produção      Técnico  12549.72

    Data_Admissao Genero  Idade Estado_Civil   Status
0      13/08/2024      F     43     Solteiro  Inativo
1      29/04/2017      F     59     Solteiro  Inativo
2      11/12/2024      F     27   Divorciado    Ativo
3      16/06/2019      M     50       Casado  Inativo
4      29/03/2019      F     62       Casado  Inativo
..            ...    ...    ...          ...      ...
995    06/05/2022      F     26        Viúvo    Ativo
996    05/06/2023      F     37        Viúvo    Ativo
997    29/12/2023      F     58     Solteiro  Inativo
998    25/12/2019      M     41     Solteiro    Ativo
999    14/11/2022      M     46        Viúvo  Inativo

[1000 rows x 10 columns]>

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

In [ ]:
# df.isnull() -> criar um tabela de true/false (true = nulo)
#

print('Quantidade de nulos por coluna: ')
print(df.isnull().sum())

print()


print('Percentual de nulos por coluna: ')
print((df.isnull))......

Quantidade de nulos por coluna:
ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

In [18]:
df.describe().round(2) # para ver estatisticas descritivas das colunas numericas e confirmar que os dados estao no formato esperado (sem valores absurdos,....)

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [ ]:
# df.nunique () -> retorna quanto valores unicos cada coluna tem

print('Valores unicos por coluna')
print(df.nunique())

Valores unicos por coluna
ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64